version: '3.5'

services:
  service-rover-web:
    container_name: service-rover-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 2000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - service-rover-be
    networks:
      - service-rover-net

  service-rover-be:
    container_name: service-rover-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2): Run "grep nameserver /etc/resolv.conf  | cut -d ' ' -f2"
    # MacOS: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=service-rover-server
    networks:
      - service-rover-net

networks:
  service-rover-net:
    external: true
